### ISSUE TITLE
请问安装devise gem后为什么rails运行不起来了？

### ISSUE THREAD

**Issue by jrconfucius** [growthschool/homework-3#73]
JrconfuciusdeiMac:~ j.r.confucius$ cd rails101
JrconfuciusdeiMac:rails101 j.r.confucius$ rails s
=> Booting Puma
=> Rails 5.0.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.2/lib/active_record/dynamic_matchers.rb:21:in `method_missing': undefined method `devise' for User (call 'User.connection' to establish a connection):Class (NoMethodError)
	from /Users/j.r.confucius/rails101/app/models/user.rb:4:in `<class:User>'
	from /Users/j.r.confucius/rails101/app/models/user.rb:1:in `<top (required)>'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:477:in `load'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:477:in `block in load_file'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:662:in `new_constants_in'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:476:in `load_file'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:375:in `block in require_or_load'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:358:in `require_or_load'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:511:in `load_missing_constant'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:203:in `const_missing'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:268:in `const_get'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:268:in `block in constantize'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `each'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `inject'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `constantize'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:583:in `get'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:614:in `constantize'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/devise-4.2.1/lib/devise.rb:305:in `get'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/devise-4.2.1/lib/devise/mapping.rb:81:in `to'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/devise-4.2.1/lib/devise/mapping.rb:76:in `modules'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/devise-4.2.1/lib/devise/mapping.rb:93:in `routes'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/devise-4.2.1/lib/devise/mapping.rb:160:in `default_used_route'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/devise-4.2.1/lib/devise/mapping.rb:70:in `initialize'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/devise-4.2.1/lib/devise.rb:335:in `new'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/devise-4.2.1/lib/devise.rb:335:in `add_mapping'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/devise-4.2.1/lib/devise/rails/routes.rb:241:in `block in devise_for'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/devise-4.2.1/lib/devise/rails/routes.rb:240:in `each'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/devise-4.2.1/lib/devise/rails/routes.rb:240:in `devise_for'
	from /Users/j.r.confucius/rails101/config/routes.rb:2:in `block in <top (required)>'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:371:in `draw'
	from /Users/j.r.confucius/rails101/config/routes.rb:1:in `<top (required)>'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.2/lib/active_support/file_update_checker.rb:77:in `execute'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/j.r.confucius/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/j.r.confucius/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/j.r.confucius/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/j.r.confucius/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/j.r.confucius/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/j.r.confucius/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/j.r.confucius/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/j.r.confucius/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/j.r.confucius/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
	from /Users/j.r.confucius/rails101/config/environment.rb:5:in `<top (required)>'
	from /Users/j.r.confucius/rails101/config.ru:3:in `require_relative'
	from /Users/j.r.confucius/rails101/config.ru:3:in `block in <main>'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from /Users/j.r.confucius/rails101/config.ru:in `new'
	from /Users/j.r.confucius/rails101/config.ru:in `<main>'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/commands/server.rb:59:in `app'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/commands/server.rb:77:in `start'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/j.r.confucius/rails101/bin/rails:9:in `require'
	from /Users/j.r.confucius/rails101/bin/rails:9:in `<top (required)>'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
	from /Users/j.r.confucius/.rvm/gems/ruby-2.3.1/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/j.r.confucius/rails101/bin/spring:15:in `require'
	from /Users/j.r.confucius/rails101/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
JrconfuciusdeiMac:rails101 j.r.confucius$

**Comment by shibinfun** [comment]
有没有 bundle install ？
